### ISSUE TITLE
Request failed with status code 404

### ISSUE THREAD

**Issue by simmons8616** [jeffijoe/typesync#19]
TypeSync v0.4.0
✖  Request failed with status code 404
Stack:
Error: Request failed with status code 404
    at createError (/usr/local/lib/node_modules/typesync/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/usr/local/lib/node_modules/typesync/node_modules/axios/lib/core/settle.js:18:12)
    at RedirectableRequest.handleResponse (/usr/local/lib/node_modules/typesync/node_modules/axios/lib/adapters/http.js:176:9)
    at emitOne (events.js:116:13)
    at RedirectableRequest.emit (events.js:211:7)
    at RedirectableRequest._processResponse (/usr/local/lib/node_modules/typesync/node_modules/follow-redirects/index.js:258:10)
    at ClientRequest.RedirectableRequest._onNativeResponse (/usr/local/lib/node_modules/typesync/node_modules/follow-redirects/index.js:39:10)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)

<img width="573" alt="machi 2018-10-17 16-46-47" src="https://user-images.githubusercontent.com/33823489/47074084-41416980-d22c-11e8-873e-859bbab3a1be.png">

**Comment by jeffijoe** [comment]
Could I see your `package.json` (you can strip out the name, just need to see all dependencies sections)?

**Comment by jeffijoe** [comment]
Nevermind, it seems the [source is down](https://github.com/Microsoft/TypeSearch/issues/25).

**Comment by simmons8616** [comment]
@jeffijoe 

> Nevermind, it seems the [source is down](https://github.com/Microsoft/TypeSearch/issues/25).

Thanks~

**Comment by jeffijoe** [comment]
@simmons8616 afraid all we can do is wait. 😄

**Comment by simmons8616** [comment]
> @simmons8616 afraid all we can do is wait. 😄

Ok，awesome plugin~

**Comment by MoonYaph** [comment]
I have the some question

**Comment by jeffijoe** [comment]
@MoonYaph nothing we can do but wait until Microsoft fixes this on their end. 😄

**Comment by andy-ms** [comment]
Hi, the blob should be public again for now.
It looks like this project could avoid using the blob though -- it doesn't really need a list of all `@types` package; it only needs to know, for each npm package installed, if there is a corresponding `@types` package for it.
The `@types` package name can be derived from the original package's name: `foo` becomes `@types/foo` and `@foo/bar` becomes `@types/foo__bar`. (There's a function `getTypesPackageName` in the TypeScript compiler if you want to see the implementation.)
Then you could just do an `npm info` request to see if that particular package exists. (You don't need to shell out to `npm`, you could just fetch from a URL like http://registry.npmjs.org/@types%2fjquery .)
The only function TypeSearch does above this is it allows you to type in the name of a global variable like `$` and discover that `@types/jquery` defines it. But if you're just looking at installed packages that isn't needed.

**Comment by jeffijoe** [comment]
Thanks @andy-ms! Yeah you are absolutely right. The reason I use the blob is mostly convenience, the package name is already mapped to the typings package.

May I ask what caused the issue?

I'll close for now. If somebody wants to take a stab at making that change, I accept PRs! 😄

**Comment by andy-ms** [comment]
We had made our blobs private under the assumption they weren't wasn't being used outside. (Forgot about TypeSearch.)

**Comment by jeffijoe** [comment]
Well I hope you don't intend to make them private intentionally anytime soon. 😄

**Comment by alash325** [comment]
@jeffijoe I have the same issue.  any ideas ?
Error: Request failed with status code 404
    at createError (C:\Users\RequiremntsTraceability\graphDB-api\node_modules\axios\lib\core\createError.js:16:15)
    at settle (C:\Users\RequiremntsTraceability\graphDB-api\node_modules\axios\lib\core\settle.js:17:12)
    at RedirectableRequest.handleResponse (C:\Users\RequiremntsTraceability\graphDB-api\node_modules\axios\lib\adapters\http.js:210:9)
    at RedirectableRequest.emit (events.js:310:20)
    at RedirectableRequest._processResponse (C:\Users\RequiremntsTraceability\graphDB-api\node_modules\follow-redirects\index.js:269:10)
    at ClientRequest.RedirectableRequest._onNativeResponse (C:\Users\RequiremntsTraceability\graphDB-api\node_modules\follow-redirects\index.js:50:10)
    at Object.onceWrapper (events.js:417:26)
    at ClientRequest.emit (events.js:310:20)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:596:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:119:17) {

**Comment by jeffijoe** [comment]
@alash325 did you try multiple times? Just ran it and it works fine for me?

**Comment by jeffijoe** [comment]
@alash325 how is this related to TypeSync? I think you might be on the wrong repo 😅

**Comment by alash325** [comment]
@jeffijoe as you said I might be on the wrong repo but I am  wondering how I ended up exactly with  the same issue.

**Comment by jeffijoe** [comment]
Probably because both use `axios` under the hood so the stack trace looks similar.
